# Generated by Django 5.2.1 on 2025-05-22 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdetails',
            old_name='name',
            new_name='username',
        ),
    ]
